logging:
  level:
    ROOT: info
    org.hibernate.SQL: INFO
    br.com.ero.airbnbcloneback: INFO

spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_URL}:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: airbnb_clone
  liquibase:
    contexts: prod
    default-schema: airbnb_clone